/*
 Name : Zeeshan 
*/
CREATE TABLE MONTHLY_REPUTATION(
	MONTHLY_REP_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT(10),
	REPUTATION LONGTEXT,
	DATE DATETIME,
	FOREIGN KEY (USER_ID) REFERENCES USER(UserID)
 );

ALTER TABLE MONTHLY_REPUTATION
MODIFY COLUMN REPUTATION NUMERIC(21,0)

CREATE TABLE NOTIFICATION(
NOTIFICATION_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
NOTIFICATION_HD TEXT,
NOTIFICATION_DTL TEXT,
CREATED_DATE DATETIME,
IS_SPECIFIC ENUM('Y','N') NOT NULL,
USER_ID INT(10),
FOREIGN KEY (USER_ID) REFERENCES USER(UserID)
);

ALTER TABLE SESSION 
MODIFY COLUMN ISACTIVE VARCHAR(20) NOT NULL;
